### ISSUE TITLE
Live Query connect operation takes forever for me

### ISSUE THREAD

**Issue by migik** [JanusMirith/ParseRealtimeQuery#1]
Hi,

I got it to work (tried both Unity 2019.4 and 2020.1), but for some reason, the initial connect time to the live query server takes almost two minutes. Both on Unity Editor and iOS. I added a simple text field to show the status of the connection, after waiting for both devices to connect I can add and move cubes and the changes are updated immediately on the other device. I'm using Back4App free tier as the backend, might this have something to do with it? Or some weird problem with WebSocket? I've been banging my head against the wall trying to figure this out for 2 days now.

**Comment by JanusMirith** [comment]
So sorry that I missed this!

That is a strange issue you are having, I tested with Back4App free as well and it was instant.
Were you able to test on different hardware or a different network?

**Comment by migik** [comment]
Hi,
Back4App support fixed this for me. When you create the live query domain, it gets a .b4a.io suffix. For some reason, the connection took about two minutes with this. They enabled my_app.back4app.io domain for me, and with that, it works! So weird. 

Btw: I also had to add this line:
`                _websocket.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;`
in WebSocketSharpClientFactory.cs Open() to make it work in another Back4App AWS region (Singapore)...

**Comment by JanusMirith** [comment]
Thanks good to know
