### ISSUE TITLE
MonobehaviourListener class missing from the project

### ISSUE THREAD

**Issue by migik** [JanusMirith/ParseRealtimeQuery#2]
RealtimeQuery.cs has these two lines:

```
            MonobehaviourListener.onApplicationQuit += Destroy;

            MonobehaviourListener.onApplicationFocus += OnFocusChanged;

```
that won't compile in Unity.

**Comment by JanusMirith** [comment]
Yep, good catch that looks to be linking to a library in Tom's code, the change was to attempt to deal with focus loss, I'll jump in and make a compliant fix to that issue and push it to master
